#!/usr/bin/bash

echo "Installing Python.."
sleep 2
pkg install -y python

echo -e "\nMove files to ~/.local/bin/..."
sleep 2

mkdir -p ~/.local/bin
cp ~/DoTask/dotask.py ~/.local/bin/dotask
chmod +x ~/.local/bin/dotask

SHELL_NAME=$(basename "$SHELL")

if [ "$SHELL_NAME" = "zsh" ]; then
    RC_FILE="$HOME/.zshrc"
elif [ "$SHELL_NAME" = "bash" ]; then
    RC_FILE="$HOME/.bashrc"
else
    echo "Unknow shell, default to .profile"
    RC_FILE="$HOME/.profile"
fi

LINE='export PATH="$HOME/.local/bin:$PATH"'
if ! grep -Fxq "$LINE" "$RC_FILE"; then
    echo "$LINE" >> "$RC_FILE"
    echo "PATH Added to $RC_FILE"
else
    echo "PATH already exists in $RC_FILE"
fi

sleep 2
echo -e "Preparation completed.."
echo -e "\nRestart shell or run: source $RC_FILE"
echo -e 'Type "dotask" to access to-do-list anywhere'
